name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "* */6 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          BLOCKS: "-#"
          IGNORED_LANGUAGES: YAML JSON TOML
          LANG_COUNT: 10
          SHOW_TOTAL: true
          TIME_RANGE: last_year
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMITTER_NAME: Jorge Mora
          COMMITTER_EMAIL: jorgemorah671@gmail.com
          AUTHOR_NAME: Jorge Mora
          AUTHOR_EMAIL: jorgemorah671@gmail.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: True
          COMMIT_USERNAME: Jorge Mora
          COMMIT_EMAIL: jorgemorah671@gmail.com
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: True
          SHOW_CODE_TOTAL_TIME: True
          SHOW_PROFILE_VIEWS: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: True
          
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
