name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          BLOCKS: "-#"
          IGNORED_LANGUAGES: YAML JSON TOML
          SHOW_TOTAL: true
          TIME_RANGE: all_time
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
